- docs/index.md
> Correct spelling mistake

- src/utils/github.ts
Currently the request path assumes the file is named after the URL:
```
/foo
/docs/foo.mdx
```
However, in some cases you might have a directory of contents with an index file. This PR adds support for the following:
```
/foo
/docs/foo/index.mdx <- primary
/docs/foo.mdx <- secondary
```
> feat: support mdxIndex path

- src/mdx/plugins/remark-undeclared-variables.ts
- src/utils/mdx-serialize.ts
- add remark plugin to convert undeclared variables to text
- added to bundler options
This will convert any node of the type `mdxFlowExpression` that is not exported using a node of type `mdxjsEsm` to a text node of the same value. It will not affect undefined components as they are given by `mdxJsxFlowElement` type.
> feat: print undeclared variables as text nodes

- src/templates/homepage/index.tsx
Mainly trying to get `docs` & `page` as key words for indexing, nothing to see here :D
> chore: tweak homepage title & description

- .github/workflows/website.yaml
- api/package.json
- api/src/app.ts
- api/src/controllers/config.ts
- api/src/controllers/github.ts
- api/src/controllers/raw.ts
- api/src/routes.ts
- api/src/utils/bundler.ts
- api/src/utils/getPlugins.ts
- api/src/utils/plugins/rehype-headings.ts
- packages/server/src/index.ts
- packages/server/src/types.ts
- website/app/components/DocsLink.tsx
- website/app/components/Documentation.tsx
- website/app/components/Errors.tsx
- website/app/components/Header.tsx
- website/app/components/Sidebar.tsx
- website/app/components/Theme.tsx
- website/app/loaders/documentation.server.ts
- website/app/routes/$owner.$repo.$.tsx
- website/app/routes/$owner.$repo.custom-styles[.]css.ts
- website/app/routes/preview.tsx
- website/app/utils/config.ts
- website/app/utils/local-preview-mode.ts
- yarn.lock
This PR adds support for maths in docs using remark-katex. To enable, you simply add the flag:
`experimentalMath: true`
in the docs.json. The extra css for Katex is injected in **only if**  this flag is set.
> feat: add math using alternative way to include css

- api/package.json
- api/src/utils/bundle.ts
- api/src/utils/github.ts
- This PR Allows different config file formats.
- makes docs.page more attractive to users in other languages
Note: examples will probably need adding to use.docs.page.
> feat: support docs.yaml and docs.toml configs

- domains.json
- repositories.json
This adds a repository/domain mapping for https://github.com/JagandeepBrar/LunaSea.
The DNS record is currently pointing to the old documentation site, but will be switched once this PR is merged to prevent minimal downtime (if it needs to be switched beforehand, please let me know).
> chore: add domain and repository mappings for LunaSea

- website/app/components/mdx/Tabs.tsx
- with remix the output seems to be minified, and so `name === TabItem` is no longer valid. Just checking the name is truthy seems to work, but i'm not sure it works for all cases here
- Fixes #162
> fix: extract tab content in remix prod

- website/app/components/ScrollSpy.tsx
- replace querySelector with getElementById, as the former does not support id selectors starting with a number
> fix: prevent infinite loop in react devtools

- domains.json
This adds a repository/domain mapping for https://github.com/widgetbook/widgetbook
> chore: add domain and repository mappings for Widgetbook

- api/src/controllers/config.ts
- api/src/controllers/github.ts
- api/src/utils/bundle.ts
- api/src/utils/github.ts
- api/src/utils/ref.ts
- website/app/context.tsx
fixes https://github.com/invertase/docs.page/issues/181
Github seems to have removed support for 'HEAD' in raw image links. This broke some default behaviour, which this PR fixes.
> fix: update ref handling on api to match github change

- docs/configuration.mdx
The link to the advanced page points to `advanced` instead of `/advanced`. Therefore, the use is directed to [https://use.docs.pageadvanced/](https://use.docs.pageadvanced/) instead of [https://use.docs.page/advanced](https://use.docs.page/advanced).
> fix: link to advanced page is broken

- docs/components.mdx
The formatting of the markdown for the out of the box image was improperly formatted. This PR fixes this.
> docs: fixed formatting of Image markdown

- website/app/components/DocsLink.tsx
- website/app/context.tsx
- website/app/utils/config.ts
Try click any links here: https://docs.widgetbook.io/~feat%2fdocs-page - and you'll notice they 404 - since the ref has `/` which isn't uri encoded
> fix: ensure ref usage is uri encoded

- api/package.json
- api/src/utils/getPlugins.ts
- yarn.lock
This PR adds support for `` .
Currently such comments are supported on Github, but make docs.page 500, for example: https://github.com/invertase/react-native-google-mobile-ads/issues/144
> feat: support html comments in mdx files

- packages/server/src/types.ts
- website/app/components/Head.tsx
- website/app/utils/config.ts
This PR adds support for google analytics and google tag manager, which is missing in v2, as raised in https://github.com/invertase/docs.page/issues/209
> feat: add GTM and GA support

- docs/configuration.mdx
- docs/frontmatter.mdx
- website/app/components/Documentation.tsx
- website/app/components/PreviousNext.tsx
- website/app/utils/config.ts
I used docs.page for my Location plugin doc, and when seeing the documentation on Mobile, it felt weird that a Previous/Next was missing
I [added it manually](https://docs.page/Lyokone/flutterlocation/features/get-location) with HTML but I was thinking that we could parse the frontmatter to easily add those.
The end result looks like this:
> feat(previous-next): add frontmatter arguments for automatically displaying next and previous buttons

- domains.json
This PR removes the go_router custom domain, which is no longer needed (since the official docs have been moved)
> chore: remove go_router domain

- api/src/bundler/plugins/rehype-code-blocks.ts
- website/app/entry.client.tsx
This PR adds support for `console` as a language choice in mdx code blocks, as requested in https://github.com/invertase/docs.page/issues/232 
It also fixes a bug on `next` preventing client side rendering.
> feat: support console language option in highlighting

- api/src/utils/bundle.ts
- api/src/utils/config.ts
This makes sure the correct link is added in the "Edit this page" button, which was broken for `index.mdx` files.
> fix: correct the link to edit this page on index files

- docs/configuration.mdx
Preview: https://use.docs.page/~277/configuration
_JSON selected_
_YAML selected_
> docs: add example for `anchors` in YAML format

- api/src/probot.ts
This PR should fix the github app, once relevant env variables are updated in deployments and on Github.
> fix: parse private key before giving it to probot

- domains.json
Adds `boxtransform.hyperdesigned.dev` domain for a doc site.
> chore: add new domain

- docs/components/zapp.mdx
- website-v3/src/components/mdx/Zapp.tsx
Based on the current Zapp! docs: https://docs.zapp.run/features/share-and-embed
I toyed with the idea of adding a different prop for each type of import (i.e. `github=""`, `gist=""`, `pub=""`), but that seems less maintainable since you would need to add a new prop whenever Zapp supports a new import location, in addition to the attributes being mutually exclusive. Instead, the current method will work for any future Zapp imports, and does not have the mutual exclusivity issue.
Note: *I have not been able to test this locally!* The setup instructions in the contributing guide were not working for me. I would appreciate it if someone here could try this PR out locally. I also have never dabbled in JSX/TSX before so apologies if I did anything weird.
> feat: allow importing Zapps from other locations

- domains.json
According to the doc, I would like to add a custom domain for my documentation.
domain: `rika2mqtt.cookiecode.dev`
should point to project `sebastienvermeille/rika2mqtt`
> chore: add entry for rika2mqtt subdomain - Update domains.json

- website-v3/src/pages/[owner]/[repository]/[...path].astro
Fix for https://github.com/leancodepl/patrol/pull/1817
> fix: handle redirect domains & refs

- domains.json
We are migrating our docs to Docusuarus but are keeping our news site on docs.page for the time being.
> chore: Remove Pieces Docs from domains.json

- docs/previews.mdx
Really stupid typo fix in `previews.mdx`
> docs: Fix typo in previews.mdx

- domains.json
This is our documentation domain for Gazelle,
our backend framework written in Dart.
Can you merge this? Would be awesome to have the docs linked to our domain :)
Thanks!
> chore: Adding Gazelle docs custom domain record
