- next-env.d.ts
- src/components/Head.tsx
- src/mdx/Heading.tsx
- src/pages/[owner]/[name]/[[...slug]].tsx
- src/templates/homepage/index.tsx
- src/utils/debug.ts
- src/utils/github.ts
- src/utils/warning.ts
- yarn.lock
- add 404 error for private repo instead of 500
- add in debug.ts utils for debug feature
> fix: 404 code for private repo

- src/components/Sidebar.tsx
previously this was comparing the whole path, when we just want to check the last part of the path.
> fix: active page indicator

- bundler/src/app.ts
- bundler/src/utils/bundle.ts
- docs/test/index.mdx
- newDomains.json
- package.json
- src/components/Header.tsx
- src/components/Sidebar.tsx
- src/hooks.tsx
- src/pages/preview.tsx
- src/templates/preview/Error.tsx
- src/templates/preview/Title.tsx
- src/templates/preview/index.tsx
- src/utils/content.ts
- src/utils/github.ts
- src/utils/preview.ts
- tsconfig.json
- yarn.lock
- added local preview mode
- manually set cors headers
> feat: local preview mode

- domains.json
Added `goconfigenv.ganeshagrawal.com` for `iamganeshagrawal/goconfigenv`
> chore: update domains.json for `iamganeshagrawal/goconfigenv`

- website/app/components/Documentation.tsx
addresses https://github.com/invertase/docs.page/issues/126
> feat: widen toc

- website/app/components/DocsLink.tsx
- website/app/components/Documentation.tsx
- website/app/routes/preview.tsx
- website/app/utils/local-preview-mode.ts
fixes https://github.com/invertase/docs.page/issues/133
> fix: reset scroll position on preview mode file change

- docs/configuration.mdx
fixes https://github.com/invertase/docs.page/issues/169
> fix: Documentation error in sidebar config

- website/app/components/mdx/Image.tsx
- website/app/routes/$owner.$repo.$.tsx
fixes https://github.com/invertase/docs.page/issues/172
> fix: import stylesheet to enable image zoom

- docs/components.mdx
- packages/dart_cli/analysis_options.yaml
- packages/dart_cli/pubspec.yaml
- website/app/components/mdx/Vimeo.tsx
- website/app/components/mdx/index.tsx
- website/package.json
- yarn.lock
This commit adds a Vimeo component, for embedding videos.
> feat: add Vimeo component

- docs/configuration.mdx
Updates docs to resolve https://github.com/invertase/docs.page/issues/187
> chore: update docs on sidebar

- docs/configuration.mdx
- website/app/components/DarkModeToggle.tsx
- website/app/components/mdx/Tweet.tsx
- website/app/context.tsx
- website/app/root.tsx
- website/app/routes/$owner.$repo.$.tsx
- website/app/styles/extra-styles.css
- website/package.json
- website/tsconfig.json
- yarn.lock
This PR replaces the imported embedded tweet component with our own. There were formatting issues with the old component that were a pain, and this gives us more control.
This should fix https://github.com/invertase/docs.page/issues/190 , https://github.com/invertase/docs.page/issues/191 and https://github.com/invertase/docs.page/issues/192 .
Notes:
- It would be nice if aligning the tweets had some use on docs.page - perhaps to add a description and allow writiing alongside.
- A nicer loading state would be preferable
> feat: new twitter embed

- website/app/components/Quicklinks.tsx
- yarn.lock
This PR fixes the href for quicklinks that appears for example on error pages.
> fix: correct quicklink hrefs

- domains.json
Updated domains.json
added new domain config for `goconfigenv.ganeshagrawal.com` => `iamganeshagrawal/goconfigenv`
> added new custom domain for iamganeshagrawal/goconfigenv

- domains.json
> feat(domain): Add docs.custom-lint.dev

- domains.json
> chore: add neorepo docs

- domains.json
Unfortunately I will have to revert this for now invertase/docs.page#290
> chore: Add Navbar router domain

- domains.json
Just wanted to get this custom domain setup for our documentation, i have already configured it on our end via registrar and CName record. Looking forward to the new domain!
> chore: add docs.pieces.app to domains.json

- domains.json
Thank you so much again has been really enjoyable working with the docs.page system and utilizing mdx! Looking forward to this "news" idea we have!
> chore: add domain news.pieces.app --> domains.json

- domains.json
Replacing releases.pieces.app github reference + subdomain with code.pieces.app sub and phoenix ref.
Getting close to our final build state! Should be only one or two more PRs over the next week to get some things cleaned up :) 
Thanks again to all of you!
> Update domains.json 

- domains.json
Hi. I would like to configure our custom domain for our documentation, I have already configured it on our side. Looking forward to it!
> chore: add new domain

- domains.json
Removing code.pieces.app as we are not going to need this domain at all and are not deploying anything here
> chore: remove code.pieces.app domain

- domains.json
Adding `docs.nizukshya.com` to domains.json
> chore: add entry for nizukshya subdomain - Update domains.json 

- domains.json
Adds docs.yaroo.dev domain for a doc site.
> chore: Update domains.json

- README.md
- website/src/layouts/homepage/index.astro
Fix homepage link to component page
> Fix component link to first in the list

- docs/getting-started.mdx
- docs/index.mdx
related
https://github.com/invertase/docs.page/pull/346
> docs: fix link

- domains.json
> chore(domains): Added docs.thabit.ai
